api:
  prod-env: false
  doc-enabled: true
logging:
  level:
    me.johnniang.apicli: DEBUG
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE